namespace ForkPlus.Git.Diff.Parsing.Tokens
{
	public enum TokenType : byte
	{
		DiffHeaderTitle,
		DiffHeaderTitleSrcPath,
		DiffHeaderTitleDstPath,
		DiffHeaderIndexSrcObject,
		DiffHeaderIndexDstObject,
		DiffHeaderIndexFileMode,
		DiffHeaderSimilarity,
		DiffHeaderCopyFrom,
		DiffHeaderCopyTo,
		DiffHeaderRenameFrom,
		DiffHeaderRenameTo,
		DiffHeaderDeletedFileMode,
		DiffHeaderNewFileMode,
		DiffHeaderOldMode,
		DiffHeaderNewMode,
		BinaryFilesDiffer,
		ChunkHeaderTitle,
		ChunkHeaderOldStart,
		ChunkHeaderOldLength,
		ChunkHeaderNewStart,
		ChunkHeaderNewLength,
		ChunkHeaderContext,
		ContextLine,
		AddedLine,
		DeletedLine,
		Pragma,
		Other
	}
}
